var:
  dubbo:
    registry:
      zookeeper: zookeeper://localhost:2181
      pieegine:
        zookeeper: zookeeper://localhost:2181
  datasource:
    username: root
    password: okmijn
    master: 47.100.53.132:3306
    slave1: 47.100.53.132:3306
    slave2: 47.100.53.132:3306

jetcache:
  statIntervalMinutes: 5
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri:
        - redis://localhost:6390
