var:
  dubbo:
    registry:
      zookeeper: zookeeper://localhost:2181
      pieegine:
        zookeeper: zookeeper://localhost:2181
  pieengine:
    appKey: 40217655fefcd9bc776af2b8910ac5f0
    appSecret: a3e59e48265cd6513f94ce9ee820f6e1
    dubbo:
      group: aws-prod
  datasource:
    username: root
    password: vLLwsZlRAoJ0@
    master: 68.79.5.94:3306
    slave1: 68.79.5.94:3306
    slave2: 68.79.5.94:3306
  jpush:
    masterSecret: 440e870ca070a801c7b9dd99
    appKey: c1a57830d9cb6c1e13926597
    apnsProduction: true
  kafka:
    servers: kafka-0.kafka-hs.pie-engine-queue.svc.cluster.local:9093,kafka-1.kafka-hs.pie-engine-queue.svc.cluster.local:9093,kafka-2.kafka-hs.pie-engine-queue.svc.cluster.local:9093


jetcache:
  statIntervalMinutes: 60
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri:
        - redis://redis.pie-engine-infra.svc.cluster.local:6379